### ISSUE TITLE
Startup at windows

### ISSUE THREAD

**Issue by Paspirine** [Razr9/Steam-Idle#1]
Is there any way to make it so that the executable starts a specific game for an unlimited amount of time? That way one could add this file to startup and every time their computer starts the game would idle.
Just throwing an idea out there... Thanks

**Comment by DevNvll** [comment]
Hello, thanks for contribution!

You can create a batch script to run multiple games for a unlimited amount of time:
```batch
@echo off
start idler.exe 33930 0
start idler.exe 24960 0
```

> the 0 means unlimited time

`idler.exe` is located inside the `bin` folder (you can get it downloading the .rar version in [releases](https://github.com/DevNvll/Steam-Idle/releases))

Unfortunately, because of a limitation in the Steamworks SDK, the `idler.exe` is unable to run before the Steam Client, and thus it would fail to run on startup.
I was thinking about creating a batch script to start multiple idlers - similar to the example above - and then putting in the startup folder. But there's no clean way a batch script could wait to a certain process to run.

I kinda forgot about this project, tbh. I was thinking about recreating it so it doesn't require steam client to be running and would support multiple accounts. However it would require to sign in to your steam account inside the app, and I don't like that. This app is meant to be simple. 
You could try something like [ArchiSteamFarm](https://github.com/JustArchi/ArchiSteamFarm)

**Comment by Paspirine** [comment]
I'm gonna stick to yours though and add a sleep argument for my startup script because ASF doesn't seem to support idling specific games anyway.Thanks!
